export enum Authority {
	ADMIN = 'ROLE_ADMIN',
	USER = 'ROLE_USER',
	CUSTOMER = 'ROLE_CUSTOMER',
	COMMISSIONER = 'ROLE_COMMISSIONER',
	GENERAL_CONTRACTOR = 'ROLE_GENERAL_CONTRACTOR',
	CONTRACTOR = 'ROLE_CONTRACTOR',
}
